


name: GitHub Pages Deploy
on:
    workflow_dispatch:
    push:
        branches:
            - master
            - dev
            - release/*
    pull_request:
        branches:
            - master
            - dev
            - release/*

permissions:
    contents: read
    # Needed for the action
    pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
    group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 14.x

            - name: Create a temporary artifact downloads folder
              run: echo  'alpha' > github-pages.txt

            - name: Use the Upload Artifact GitHub Action
              uses: actions/upload-artifact@v4
              with:
                  name: github-pages
                  path: ${{ github.workspace }}

    # Add a dependency to the build job
    deploy:
        runs-on: ubuntu-latest
        needs: build

        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write # to deploy to Pages
            id-token: write # to verify the deployment originates from an appropriate source

        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{steps.deployment.outputs.page_url}}

        # Specify runner + deployment step
        steps:
            - name: Deploy to GitHub Pages
              uses: actions/download-artifact@v4
              with:
                  name: github-pages
                  path: .
#             - uses: actions/configure-pages@v1
#               with:
#                   token: ${{ secrets.DEPLOY_TOKEN }}
            - uses: actions/upload-pages-artifact@main
              with:
                  path: .
                  
            - run: | 
                   npm install
                   npm install pm2 -g

            - id: deployment
              uses: actions/deploy-pages@main
            - run: pm2 start node "index.js"

            # - run: npm run build
            # - run: mkdir github-pages-deploy-action-temp-deployment-folder
            # - run: mkdir build
            # - run: ls
            # - name: Deploy 🚀
            # uses: JamesIves/github-pages-deploy-action@v4
            # with:
            # folder: build # The folder the action should deploy.
